TrackaryASP/Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TrackaryASP.Models
{
    public class Product : IComparable<Product>
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        public string Description { get; set; }

        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Reward Cashback")]
        public decimal Reward { get; set; }

        [Range(0, 1000)]
        public int Quantity { get; set; }

        public bool InStock
        {
            get
            {
                return Quantity > 0;
            }
        }

        [DataType(DataType.ImageUrl)]
        public string Image { get; set; }

        public int CompareTo(Product other)
        {
            return String.Compare(this.Name, other.Name, StringComparison.OrdinalIgnoreCase);
        }
    }
}

TrackaryASP/Controllers/CartController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using TrackaryASP.Models;

namespace TrackaryASP.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private TrackaryDbContext db = new TrackaryDbContext();

        // GET: Cart/Checkout
        public ActionResult Checkout()
        {
            return View();
        }

        // POST: Cart/AddItem/2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Cart cartData;
            if (this.Session["CartData"] == null)
            {
                cartData = new Cart { };

                this.Session["CartData"] = cartData;
            }
            else
            {
                cartData = this.Session["CartData"] as Cart;
            }

            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            // Add item to cart (if available), and update the item's quantity
            if (cartData.Add(product))
            {
                product.Quantity--;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Products");
        }

        // POST: Cart/Clear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Clear()
        {
            // Restore item quantities
            foreach (ProductDictionary p in (this.Session["CartData"] as Cart).Products)
            {
                Product product = db.Products.Find(p.Key.ID);
                if (product != null)
                {
                    product.Quantity += p.Value;
                    db.Entry(product).State = EntityState.Modified;
                }
            }

            db.SaveChanges();

            this.Session["CartData"] = null;

            return RedirectToAction("Index", "Products");
        }
    }
}

TrackaryASP/Controllers/ProductsController.cs
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TrackaryASP.Models;

namespace TrackaryASP.Controllers
{
    public class ProductsController : Controller
    {
        private TrackaryDbContext db = new TrackaryDbContext();

        // GET: Products
        public ActionResult Index()
        {
            if (this.Session["CartData"] == null)
            {
                var cartData = new Cart { };
                this.Session["CartData"] = cartData;
            }

            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "ID,Name,Description,Price,Reward,Quantity,Image")] Product product, 
            HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                UploadImage(product, Image);
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "ID,Name,Description,Price,Reward,Quantity,Image")] Product product, 
            HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                UploadImage(product, Image);

                db.Products.Attach(product);

                var entry = db.Entry(product);
                entry.State = EntityState.Modified;

                if (Image == null)
                {
                    entry.Property(e => e.Image).IsModified = false;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Product product = db.Products.Find(id);
                db.Products.Remove(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException)
            {
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void UploadImage(Product product, HttpPostedFileBase Image)
        {
            if (Image != null)
            {
                string imagePath = "~/Images/";
                if (!System.IO.Directory.Exists(Server.MapPath(imagePath)))
                    System.IO.Directory.CreateDirectory(Server.MapPath(imagePath));

                Image.SaveAs(HttpContext.Server.MapPath(imagePath) + Image.FileName);
                product.Image = Image.FileName;
            }
        }
    }
}

TrackaryASP/Controllers/TransactionsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TrackaryASP.Models;
using TrackaryASP.ViewModels;

namespace TrackaryASP.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private TrackaryDbContext db = new TrackaryDbContext();

        // GET: Transactions
        public ActionResult Index()
        {
            return View(db.Transactions.ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: Transactions/Checkout
        public ActionResult Checkout()
        {
            var viewModel = new TransactionCustomerViewModel();
            viewModel.Customers = db.Customers;
            return View(viewModel);
        }

        // POST: Transactions/Checkout
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout([Bind(Include = "ID")] Transaction transaction, TransactionCustomerViewModel viewModel)
        {
            if (ModelState.IsValid && this.Session["CartData"] != null)
            {
                // Cart contents and total cost
                Cart cart = this.Session["CartData"] as Cart;

                // Only proceed if there's actually things in the Cart
                if (cart.TotalCost > 0)
                {
                    transaction.Amount = cart.TotalCost;
                    transaction.Rewards = cart.TotalReward;
                    transaction.Items = cart.ToString();
                    this.Session["CartData"] = null;

                    // Current date and time
                    transaction.TransactionDateTime = DateTime.Now;

                    // (Optional) purchaser
                    if (viewModel.PickedCustomerID != null)
                    {
                        Customer purchaser = db.Customers.Find(viewModel.PickedCustomerID);
                        if (purchaser != null)
                        {
                            // Associate this Transaction with the Customer
                            transaction.Customer = purchaser;

                            // Add rewards to Customer's account
                            purchaser.Rewards += cart.TotalReward;
                        }
                    }

                    db.Transactions.Add(transaction);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Products");
                }
            }

            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrackaryASP/Views/Products/Create.cshtml
@model TrackaryASP.Models.Product

@{
    ViewBag.Title = "New Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Products", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h2>New Product</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reward, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reward, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reward, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" readonly="" class="form-control floating-label" placeholder="Browse...">
                <input type="file" accept=".png,.jpg" id="Image" name="Image">
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
                <input type="submit" value="Add product" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrackaryASP/Views/Products/Delete.cshtml
@model TrackaryASP.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reward)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reward)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-lg-10 col-lg-offset-2">
            <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

TrackaryASP/Views/Products/Details.cshtml
@model TrackaryASP.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<h4>Product</h4>
<hr />        

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Price)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Price)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Reward)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Reward)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Quantity)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Quantity)
    </dd>
</dl>

TrackaryASP/Views/Products/Edit.cshtml
@model TrackaryASP.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Products", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Edit Product</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reward, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reward, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reward, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" readonly="" class="form-control floating-label" placeholder="Browse...">
                <input type="file" accept=".png,.jpg" id="Image" name="Image">
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a href="@Url.Action("Index")" class="btn btn-default">Cancel</a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrackaryASP/Views/Products/Index.cshtml
@model IEnumerable<TrackaryASP.Models.Product>

@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_FluidLayout.cshtml";
}

<div class="row">
    @if (Request.IsAuthenticated)
    {
        <div class="col-md-4 col-md-push-8">
            <div class="panel panel-default clearfix">
                <div class="panel-heading">
                    <h2>Cart</h2>
                </div>

                <div class="panel-body">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Item</th>
                                <th>Unit Price</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in (Session["CartData"] as TrackaryASP.Models.Cart).Products)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(productItem => item.Key.Name)</td>
                                    <td>@Html.DisplayFor(productItem => item.Key.Price)</td>
                                    <td>@Html.DisplayFor(productItem => item.Value)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <p id="cart-total">Total: $@((Session["CartData"] as TrackaryASP.Models.Cart).TotalCost)</p>
                        @using (Html.BeginForm("Clear", "Cart", FormMethod.Post, new { id = "cart-clear" }))
                        {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-default">Clear</button>
                        }
                        <a href="@Url.Action("Checkout", "Transactions")" class="btn btn-primary">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="@(Request.IsAuthenticated ? "col-md-8 col-md-pull-4" : "col-md-12")" id="@(Request.IsAuthenticated ? "products-list" : "")">
        <h2>Products</h2>

        <div class="fab-container">
            @if (Request.IsAuthenticated)
            {
                <a href="@Url.Action("Create")" class="btn btn-primary btn-fab btn-raised mdi-content-add"></a>
            }

            <ul id="products-grid">
                @foreach (var item in Model)
                {
                    <li class="product-item panel panel-default">
                        <div class="panel-body">
                            <div class="panel-heading">
                                @if (item.Image != null)
                                {
                                    <img src="~/Images/@Url.Content(item.Image)" alt="Product image" />
                                }
                            </div>
                            <h2>
                                @Html.ActionLink(item.Name, "Details", new { id = item.ID })
                            </h2>
                            <h3>
                                @Html.DisplayFor(modelItem => item.Price)
                            </h3>
                            <p>
                                @Html.DisplayFor(modelItem => item.Description)
                            </p>
                            <p>
                                Reward: @Html.DisplayFor(modelItem => item.Reward)
                            </p>
                            <p>
                                @if (item.InStock)
                                {
                                    @Html.Raw("Quantity: ")
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                }
                                else
                                {
                                    @Html.Raw("Out of stock")
                                }
                            </p>
                        </div>

                        @if (item.InStock && Request.IsAuthenticated)
                        {
                            <div class="panel-footer">
                                @using (Html.BeginForm("AddItem", "Cart", new { ID = item.ID }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    <input type="submit" value="Add to cart" class="btn btn-default" />
                                }
                            </div>
                        }
                    </li>
                }
            </ul>
        </div>
    </div>
</div>